version: "3.8"

services:
  mysql8: # 自訂的service
    image: mysql:8
    container_name: mysql8
    volumes:
      - ~/mysql-docker-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: demo
    ports:
      - "3306:3306"